[tool.poetry]
name = "demoexam2023"
version = "0.1.0"
description = ""
authors = ["dmitry <kalibdune@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyqt6 = "^6.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
